name: Daily AI Note

on:
  schedule:
    - cron: '23 13 * * *'  
  workflow_dispatch:

jobs:
  generate-note:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate AI-like daily note
        run: |
          mkdir -p logs
          NOW=$(date '+%Y-%m-%d')
          FILE="logs/$NOW-hoc-hang-ngay.md"
      
          # Đọc danh sách note từ file
          mapfile -t NOTES < notes.txt
      
          RANDOM_INDEX=$((RANDOM % ${#NOTES[@]}))
          NOTE=${NOTES[$RANDOM_INDEX]}
      
          echo "# Dev Note - $NOW" > "$FILE"
          echo "" >> "$FILE"
          echo "$NOTE" >> "$FILE"

      - name: Commit and push
        run: |
          git config user.name "giang"
          git config user.email "giangairdrop002@gmail.com"
          git add logs/
          git commit -m "🧠 Daily AI Note for $(date '+%Y-%m-%d')" || echo "Không có gì để commit"
          git pull --rebase
          git push
